### ISSUE TITLE
Allow the user to bind Undo and Redo

### ISSUE THREAD

**Issue by tsimonq2** [tsujan/FeatherNotes#10]
I'm personally used to pressing `Ctrl + Y` for the redo function on a text editor. FeatherPad uses `Ctrl + Shift + Z`; which is fine (changing the defaults is a separate issue), but I should be able to bind it with all the other shortcuts.

**Comment by tsujan** [comment]
I made the undo/redo/cut/copy/paste shortcuts unchangeable because they were set by Qt in the context menu. Now that the context menu is changed and has additional items (Paste Date and Time, Open Link, Copy Link), I think we can have customized shortcuts for those actions.

It may take a while because I'm working on another part of the code but I'll tell you when it's ready.
Thanks for the suggestion!

**Comment by tsujan** [comment]
Oh, this is FeatherNotes! You meant FeatherPad; didn't you?

FeatherNotes needs lots of polishing, which I'll do when I find the time. For now, my focus is on FeatherPad.

**Comment by tsimonq2** [comment]
Ohhhhh, you're right

My mistake, opening an issue there :)

**Comment by tsujan** [comment]
It's OK.

**Comment by tsimonq2** [comment]
https://github.com/tsujan/FeatherPad/issues/92
