### ISSUE TITLE
Faulty context menu of menubar and toolbar

### ISSUE THREAD

**Issue by pmattern** [tsujan/FeatherNotes#2]
Both over menubar and toolbar there's a context menu which is apparently meant to toggle the display of toolbar and search bar but which lacks labelling
![feathernotes_faulty-context-menu](https://cloud.githubusercontent.com/assets/9860801/23580522/e952a6e4-0103-11e7-8778-20495d50d697.png)

While it's probably obvious the menu should not remain as it is I'm not so sure what's the best fix. Personally, I'd tend to propose to not fix the menu but drop it altogether and include its options into the preferences dialogue. This would be consistent with FeatherPad, too.

**Comment by tsujan** [comment]
Oh, I forgot to remove those Qt-enforced menus from FeatherNotes! Thanks! Will remove them soon.

**Comment by pmattern** [comment]
As of 367e94c the weird menu is gone, but the GUI no longer provides any means to toggle the display of menubar and toolbar.
Wouldn't it be good to e. g. add corresponding options to the preferences dialogue? While at it you could also consider adding on option to have the search bar displayed permanently. All similar to what is implemented in FeatherPad already.

**Comment by tsujan** [comment]
The reason why I didn't implement those options in FN wasn't forgetfulness: since I don't start any session without starting FN with it, I've noticed that menubar and toolbar are always needed (because of rich text editing), while searchbar isn't. In short, the reason was my experience with notes managers.

However, the settings in question seem harmless when optional; so I may add them after giving them some thought.

BTW, that weird context menu is created by Qt Designer and isn't a good way of hiding menu/tool bar because it may remove some keyboard shortcuts. I remember pacmanfm-qt had it too and I or someone else removed it.

**Comment by pmattern** [comment]
I'm not an expert in notes manager, but so far I'm performing most of the actions like editing the tree or content in the right pane by keyboard only. So I think using the GUI without menu bar and toolbar can work and make sense at times e. g. to save some space on not so large displays.

**Comment by tsujan** [comment]
OK, I'll add all of them tomorrow after a minor fix. As a mouse user, I didn't see that others might be comfortable with shortcuts.

**Comment by tsujan** [comment]
Added options to hide menubar or toolbar. Tested them and they seem to work OK but your test would be appreciated.

**Comment by pmattern** [comment]
Both options work as expected.
The one to hide the menu bar lacks a mnemonic.
How about adding another option addressing the search bar, similar to the one in the preferences of FeatherPad?

**Comment by tsujan** [comment]
> The one to hide the menu bar lacks a mnemonic.

Oh, I was aware of it but forgot it in the end :)

> How about adding another option addressing the search bar...

Yes, will add it too.
