### ISSUE TITLE
Sorting feature

### ISSUE THREAD

**Issue by data-man** [tsujan/FeatherNotes#230]
E.g. like Sublime Text, in `Edit` menu:
`Sort Lines                   F9`
`Sort Lines (Case Sensitive)  Ctrl-F9`

Additionally, it would be great to sort tables by selected column.

**Comment by tsujan** [comment]
Thanks for your suggestion but FeatherNotes is a notes manager, not a code editor. The feature you requested was implemented in [FeatherPad](https://github.com/tsujan/FeatherPad) a long time ago (FeatherPad is text/code editor).

**Comment by data-man** [comment]
> FeatherNotes is a notes manager, not a code editor. 

Sure, but I want sort lines in my notes too. :smile:

**Comment by tsujan** [comment]
I understand but some functionalities are more useful with text editors, some with notes managers.

For example, I could transfer the whole code of syntax highlighting that I've written for FeatherPad to FeatherNotes but it wouldn't be practical because FeatherNotes isn't intended for highlighting codes. And similarly, the codes for case changing (to lower/upper/start case), converting tabs to spaces, moving lines/paragraphs, etc.

**Comment by data-man** [comment]
I'm sorry, but I disagree.
Note managers are similar to word processors that have this functionality.
