### ISSUE TITLE
Option to remember window size doesn't cover maximized windows

### ISSUE THREAD

**Issue by pmattern** [tsujan/FeatherNotes#246]
Title says it basically all.

Steps to reproduce:
1. Make sure "Remember window size" is checked in preferences' tab "Window".
2. Start and stop FeatherNotes several times, each time changing the window size. These different window sizes will be remembered. Keep in mind the last of them.
3. Maximize the window and restart FeatherNotes. The window will not come up maximized. Rather, its size will be the last one of step 2.

Btw. FeatherPad is not affected by this problem.

707c3067 and tsujan/FeatherPad@f086644f via their respective AUR VCS packages on Arch Linux.

**Comment by tsujan** [comment]
FeatherNotes only remembers the size, not the state (= maximized or fullscreen). When a window is maximized, its size is that the window before maximization.

I don't remember why I didn't make FeatherNotes remember the state. There might have been a complication related to systray. But will look into it soon. Thanks for the reports!

**Comment by tsujan** [comment]
I found the real reason: remembering the position, size and state was tricky — especially with window translucency.

Actually, FeatherPad also does it incorrectly. For example:

 1. Make FeatherPad remember both size and position.
 2. Put its window somewhere.
 3. Maximize it.
 4. Close it.
 5. Open a window.
 6. Unmaximize it.

Then, the position at step (2) won't be restored.

However, I found a way of doing it correctly. Will make two commits, for FeatherPad and FeatherNotes.

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/FeatherNotes/commit/1039a28640088bd9423937332d1c644ca7a1af3a

FeatherPad's problems are also fixed, a little differently.

**Comment by pmattern** [comment]
Both the problem I posted about FeatherNotes and the one you added about FeatherPad seem to be fixed in both applications here, too.

While testing I happened to realize that in FeatherNotes both the option to memorize size and the one to memorize position are enabled by default, while in FeatherPad it's only the former. Also, the wording is quite different in the two applications' GUIs besides the function is actually the same.
Maybe it would make sense to adjust that a little. But YMMV, of course.

**Comment by tsujan** [comment]
Thanks for testing! They passed my tests too.

FeatherPad's option was added later (@agaida wanted it). It has a tool-tip, saying, "Enforcing a window position is not recommended...". IMO, only special apps should do it. A notes manager is such an app, because of its job; a text editor or file manager isn't. That's the reason it's disabled by default in FeatherPad.

As for the texts, I think they're explanatory in both cases. FeatherPad and FeatherNotes are independent of each other. But, more importantly, I don't want to break the current translations.

Under X11, if a WM can't handle window positions correctly, it should have a bug. But, sadly, remembering the window position isn't possible under Wayland — or one can say that Wayland is buggy from its core.
