### ISSUE TITLE
Unable to remap rename shortcut with hunspell enabled

### ISSUE THREAD

**Issue by Dialga** [tsujan/FeatherNotes#261]
Currently if feathernotes was built without hunspell pressing F2 on a node will rename the node, which I prefer, but if hunspell is enabled the action changes to spellcheck the first word in the note. Now I want to remap spellcheck to F7 - which is the shortcut used in Microsoft Word and Libreoffice writer to spellcheck but an error occurs "The typed shortcut was[is] reserved". Now it's possible to remap spell check to F1 but that is counter-intuitive as F1 is normally used for help, which Ctrl+H does. Keeping Ctrl+Shift+R and F2 for renaming the current node would be nice with hunspell enabled.

**Comment by tsujan** [comment]
Each app has its specific structure, which can be very different from others. In FeatherNotes, some shortcuts are reserved for the most important jobs and can't be changed. For example, `F3-F10` are for search/replacement actions. Since those actions are used frequently and because `F3` and `F4` are for forward and backward search in most apps, choosing the other `Fx` keys for other search/replacement jobs is the most natural approach.

We can expect that `Ctrl+A` should select "everything" everywhere, but what a key like `F7` does depends on the app.

That being said, you could assign `Ctr+F7` or `Alt+F7` to spell-checking and `F2` to node renaming.
