### ISSUE TITLE
Option to keep static node list

### ISSUE THREAD

**Issue by Dialga** [tsujan/FeatherNotes#273]
In the current version of feathernotes, if you click on a note that is 3 or more nodes deep, the tree list would immediately shift to the left, and continues to shift with every deeper node level. This is visually distracting, plus cuts off the beginning of all other notes in a higher depth. This occurs if there exists a node with a long name.
It would be immensely helpful to keep the notes tree list static, so it doesn't shift horizontally with each additional node depth.

**Comment by tsujan** [comment]
That's intentional. The selected node's text should be made visible as far as possible, both vertically and horizontally. Qt does the first part but, because of a bug, not the second. The code includes a workaround for that bug.

What you call static node isn't practical. Increase the side-pane width if you want to see all or more nodes — as you would with a static tree.
