### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by emmggi** [tsujan/FeatherNotes#278]
Could you please add a tab in settings to paste our own qss for the application?

What chance is there for encryption and sync to google drive/dropbox/self hosting?

**Comment by tsujan** [comment]
> Could you please add a tab in settings to paste our own qss for the application?

QSS has no relation to FeatherNotes. The GUI is styled by the active Qt style, as all Qt apps should (it's called platform integration). Only the view and its default text can have different colors.

> What chance is there for encryption

When a note is password-protected, it's encrypted (also, see Help). 

> sync to google drive/dropbox/self hosting?

These jobs have their own apps (like `rclone`).

**Comment by emmggi** [comment]
What I meant to say is make the UI nicer. My theme is Yaru which makes most apps pretty nice but this one is still pretty 2000s looking.

> When a note is password-protected, it's encrypted (also, see Help).

Didn't see this, although I meant app-wide password protection not per node.

> These jobs have their own apps (like rclone).

That may be true but integrating it into this app is what I meant (ie not running the command every time, instead have the app do it itself before exit, when hitting a shortcut etc).

**Comment by tsujan** [comment]
> What I meant to say is make the UI nicer.

Like in any Qt app, how the UI looks depends on the Qt style:

![ui](https://user-images.githubusercontent.com/981076/187032794-c754b4fc-dac8-43ca-b3b3-a781c46961cc.png)

QSS doesn't style Qt apps automatically; it needs to be hard-coded first. Adding hard-coded styles to apps is a bad practice because, among other things, it breaks platform integration.

> That may be true but integrating it into this app...

I follow the Unix philosophy: "Make each program do one thing well." This is a Notes Manager; it shouldn't do the job of `rclone`, `wget`, or even FeatherPad (code editing).
