### ISSUE TITLE
Styling regression

### ISSUE THREAD

**Issue by ivan-avalos** [tsujan/FeatherNotes#281]
Hey! Of all the notes apps I've tried to use for taking notes, this is the one that has worked better for me, and I really love it. It's been almost a year since I started using it. Thanks for your work!

With the last version, 1.0.0, the styling from the active Qt theme is not respected. I'm using KDE Breeze, and it seems like FeatherNotes is using Qt's default (Fusion). There's also the systray regression, but that was already reported.

**Comment by tsujan** [comment]
There is no regression. The reason is as simple as this: Your distro has compiled FeatherNotes against Qt6 (as Arch has done recently), but KDE doesn't support Qt6 styling yet.

The default compilation is still against Qt5. If you use Arch and can work with `makepkg`, you could remove `-DENABLE_QT5=OFF` from its [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/feathernotes/trunk/PKGBUILD) and recompile FeatherNotes. If you do so, change `pkgrel` to 2 or higher.
