### ISSUE TITLE
Menu shortcut

### ISSUE THREAD

**Issue by Cherkah** [tsujan/FeatherNotes#313]
what is the menu shortcut ?

the sandwich icon of the software (in wayland kde) does not appear in the menu bar; no problem with X11
+ impossible to find it (the menu shortcut)  in the help section (ctrl + H).

thanks

**Comment by tsujan** [comment]
> the sandwich icon of the software (in wayland kde) does not appear in the menu bar

FeatherNotes doesn't have any icon on its menubar. If by "sandwich icon" you mean the button that appears on the *toolbar* when the menubar is hidden, it doesn't need a shortcut; toolbar buttons should be pressed.

Anyway, you weren't specific, but your problem seems to about Plasma-Wayland — although Plasma-Wayland has no problem with FeatherNotes here.
