### ISSUE TITLE
Free RAM

### ISSUE THREAD

**Issue by Rasterisko** [tsujan/FeatherNotes#340]
Hello, Tsujan!
As we open the notes, they are loaded into the RAM memory making the consumption becomes very high if we have a lot of notes and images. Would it be possible for the application to remove notes that are not open from the RAM memory or something similar?

Thanks!

**Comment by tsujan** [comment]
Hi,

FeatherNote's memory usage is minimal — it even doesn't load nodes of a note into the GUI until they are viewed — and it has no memory leak as far as I've checked. The rest is about how Qt uses the memory and, in the end, how the kernel manages it.

Extreme case are extreme by definition.

For reasons beyond this comment, FeatherNotes became a single-instance app since V1.0.0. If you've opened an extremely heavy note and then want to open a lighter one instead, without leaving the memory management to Qt/kernel, you could first quit the app.
