### ISSUE TITLE
Feature Request: Linking notes

### ISSUE THREAD

**Issue by Rasterisko** [tsujan/FeatherNotes#341]
Hello again, Tsujan!

We can link to URL and LOCATION. What do you think if we could link other notes? Then, clicking on the link would open the linked note.

**Comment by tsujan** [comment]
Notes are files; they can already be linked (and I use that).

**Comment by tsujan** [comment]
> I'd like to be able to link to a node so it can be opened. Something like this:

There's no plan to implement that because node names are searchable, and to keep FeatherNotes lightweight, I avoid cluttering its code for unnecessary features.

**Comment by tsujan** [comment]
I've had a hard time to make a balance between features and lightweightness; otherwise, I haven't been against new features at all. In particular (and as I've mentioned here and there), closing a report doesn't mean that its requested feature isn't valid.

Not only node names are searchable, but also you could add (hidden) tags to them and search in them. For example, some nodes may be about "thoughts and ideas". If you add a tag like "thought, idea" to them, you could search in tags by typing "thought" or "idea" and find them.
