### ISSUE TITLE
Paste as HTML changes the spacing lines

### ISSUE THREAD

**Issue by Rasterisko** [tsujan/FeatherNotes#343]
Hello again, Tsu Jan!

I've noticed that when copyng text and pasting as HTML, the spacing between the lines changes. Obviously at first I thought it was a characteristic of the original text from which I copied. But using Libreoffice Writer I removed all space between lines and the paste as HTML still change the space of lines in FeatherNotes. And even using "Clear all formats" I can't change back for the default spacing. I don't know if this spacing is standard for HTML or something like that, but would it be possible to use this "paste as HTML" and always continue with the default line spacing of FeatherNotes?

Thank you for your attention!

**Comment by tsujan** [comment]
Feathernotes'  "Paste HTML" pastes exactly what is copied. Perhaps Libreoffice changes something. Could you provide an example?

**Comment by tsujan** [comment]
I meant a text that I could copy. Anyway, I found one and saw your point.

`margin-top` and `margin-bottom` are inherited from the pasted lines, and there's no way to remove them. This may be a new bug in Qt :( Thanks for telling me about it! I should find a workaround.

In the meanwhile, you could paste the HTML-formatted line *before an empty new-line*, for the following lines not to inherit those styles. (I've always had that habit; hence not noticing the issue before).

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/FeatherNotes/commit/559fb5b788189d11dcda7a3cfaec88ce2ae05ca9. Now the block format is also removed: just select the text you want to have the default format and press "Clear all formats", as before.

If you use git FeatherNotes, you could upgrade now; otherwise, the fix will be in the next release, i.e.,  1.1.2 (I'm not sure when I'll make it).

Thank you very much for finding and reporting the problem! Nice catch!
