### ISSUE TITLE
Using system icons should be possible

### ISSUE THREAD

**Issue by pmattern** [tsujan/FeatherNotes#4]
Restricting FeatherNotes to its own built-in icon theme was certainly done for a reason, in particular to make sure an icon theme is used which is covering all icons needed by the application. But this practice breaks the consistency of a desktop session to some degree and makes FeatherNotes look like a stranger, in particular regarding the toolbar.

IMO a compromise addressing both problems could be to turn the use of the built-in icon theme into an option which is enabled by default, much as it's done by FeatherPad.
I think the need to enable system icons on purpose will make users realize that it's due to this selection when icons go missing. That way they could decide and choose which of the two potential drawbacks depicted above is more important to them.

**Comment by tsujan** [comment]
Yes, this is a real problem. As you mentioned, some of icons aren't found in some icon sets. Table icons, for example, can be found only in some KDE icons sets, as far as I know. So, if I add an option for system icons, some items will remain iconless.

On the other hand, the name of some icons are different in KDE and GTK icon themes.

Yet there's another problem. I can add a condition so that, if an icon exists in the system theme, it's used instead of own icons and if not, the internal icons are used. But Qt's behavior is strange in such cases. The icon may not exist in the theme but Qt may not report it as Null.

The last problem, which is related to the above-mentioned one, is that GTK DE's may not be able to give icons to Qt apps and I haven't found a reliable way of detecting that yet.

Maybe the best method is what you proposed: adding an option for system icons and letting users decide for themselves. I'll do so if I can't find another way.

**Comment by tsujan** [comment]
Done!
I solved the problem with a logically trivial but practically cumbersome method (writing similar lines of code again and again... because Qt can't get icon names from Qt Designer!).

Now, there's an option for using own icons in Preferences. If it's unchecked, FeatherNotes will try to use system icons in such a way that if there is a system icon for an action/button, it'll be used but if not, the corresponding internal icon will be used.

Among the icon themes installed here, Breeze, Oxygen and my own icon sets were complete. The Gnome icon theme lacked just a few icons. The worst of all was hicolor, of course, but even with it, there was no missing icon.

**Comment by pmattern** [comment]
Running 5cc8741 on Arch Linux under LXQt using the system icons is working as expected. This includes changing the icon theme by `lxqt-config-appearance`.

There are two minor details in the tooltip of the new option in dialogue "Preferences" I would suggest to change.
Personally, I think exclamation marks in contexts like this are a bit of an exaggeration and a simple dot is better. A dot in turn should be at the end of the second sentence as well to be consistent both in this particular tooltip and with the other ones.

What you say about QtDesigner seems pretty odd to me but is beyond what I can judge.

Btw. Numix seems to be another icon theme providing all icons needed by FeatherNotes.
Theme hicolor on the other hand is only meant to provide custom icons of applications which are not covered by the Icon Naming Specification, AFAIK. To my knowledge none of the usual GUIs to select the icon theme including `lxqt-config-appearance` allows for selecting hicolor in the first place. So it wouldn't even matter at all if it lacked some of the icons needed by FeatherNotes.

**Comment by tsujan** [comment]
Thanks for testing and commenting! I'll remove the exclamation mark(s).

hicolor just showed me that the new code should be fine; I knew about its purpose.

And yes, I tried Numix once and saw that it was a pretty comprehensive icon set.

**Comment by Imerion** [comment]
Sorry for opening this old issue. I was just about to suggest an option to use system icons and did a search first and found this. It would be really nice to have colorful icons matching the rest of my system using the Oxygen icon theme. However, I cannot find the option in Preferences that is referred to here. I am using Feathernotes 1.1.0, using KDE Neon on one system and Lubuntu with LXQT on the other.

**Comment by tsujan** [comment]
This report is very old.

A long time ago, I added SVG symbolic icons, that change color to have high contrast with their backgrounds, and removed the system icon support because many important icons may not be found in well-known icon sets.

I don't want the risk of an incomplete GUI under any desktop environment, and the amount of needed computations for checking the existence of system icons isn't acceptable.

**Comment by Imerion** [comment]
I see. I'm sorry to hear that but I understand. It would be an option defaulting to off, but I can see it would take a lot of work to implement. Thanks for the quick answer and for writing great software!

**Comment by tsujan** [comment]
> it would take a lot of work to implement.

It's rather about the ugliness of extra computations that might only result in GUI inconsistency (using internal icons when they aren't found in the system and leaving the others to the system). Also, SVG icons are very light and always clearly visible.

In contrast, [FeatherPad](https://github.com/tsujan/FeatherPad) has an option for system icons because it only has a few icons that may not be found in all system themes —  they're always internal.
