### ISSUE TITLE
Depends on x11

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherNotes#40]
Hello.
It looks like the projects depends on some x11 headers. That prevents it from running on Wayland-based desktops and causes build failure on Mac OS
Is it possible to make all the x11-related code optional? Would such changes be merged if I leave a PR?
P. S. I know Macs have limited x11 support with Quarz, but I didn't try this

**Comment by tsujan** [comment]
Both FeatherPad and FeatherNotes work well under wayland in Linux. The X11 dependency is necessary because wayland is still a very poor experience compared to X11. The app recognizes wayland when run under it and "forgets" about X11.

So, the X11 code shouldn't be optional.

As you know, I know nothing about macOS ;)

**Comment by shlyakpavel** [comment]
> Both FeatherPad and FeatherNotes work well under wayland in Linux. The X11 dependency is necessary because wayland is still a very poor experience compared to X11. The app recognizes wayland when run under it and "forgets" about X11.
> 
> So, the X11 code shouldn't be optional.
> 
Under xwayland?

**Comment by shlyakpavel** [comment]
Look here
https://github.com/tsujan/FeatherNotes/blob/master/feathernotes/x11.h
On x11 you have https://github.com/tsujan/FeatherNotes/blob/c7ce64e1877429653355ed03e3565c9da1d088e0/feathernotes/x11.h#L21-L23
On systems without x11 (including pure Wayland, Mac OS, Windows, Android, whatever)
https://github.com/tsujan/FeatherNotes/blob/c7ce64e1877429653355ed03e3565c9da1d088e0/feathernotes/x11.h#L31
`Window` is undefined
You do not have such problems in FeatherPad

**Comment by tsujan** [comment]
Depending on X11 and really working under wayland are not opposite to each other in Linux.

Your problem is very different and only exists in Mac because Mac doesn't have X11. Its solution is very easy. For now, I've prioritized other works (bug fixes). Later, I'll make X11 dependency optional in FeatherNotes too.

**Comment by shlyakpavel** [comment]
> Your problem is very different and only exists in Mac because Mac doesn't have X11. 
1. And also on Windows and Android
2. Just a fact: mac has optional x11 server
Good luck with bugfixing :)

**Comment by tsujan** [comment]
> And also on Windows and Android

I'll never ever support MS Windows or Android ;) Mac is different....

> Just a fact: mac has optional x11 server

You won't need it. I'll remove the X11 dependency *for mac*. I might also ask for your help if needed.

**Comment by tsujan** [comment]
Yes, I left a comment there. Both PRs will be either merged or included in a big commit (that fixes several issues -- not finished yet). Thanks again!

**Comment by tsujan** [comment]
Closed because of https://github.com/tsujan/FeatherNotes/commit/242f971579a1c4f290e280b9e38c0ebc1431e864
