### ISSUE TITLE
Optional toolbar button size

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherNotes#45]
Unlike FeatherPad, FeatherNotes have *really tiny* items on toolbar
<img width="796" alt="image" src="https://user-images.githubusercontent.com/19782228/51126895-4a46d480-1835-11e9-911e-a71b41f2d81d.png">
It's a pain on 13 inch 4k screen (in any OS)
Is there any possibility to improve it?
I'm sorry for leaving so many issues :) I really like the software and I'd love to see it improving and developing :)
Have a nice day!

**Comment by tsujan** [comment]
FeatherNotes already supports HiDPI and your screenshot proves that ;) The toolbar is correct: the icon size is 16, which is enlarged to 32px with the scale factor of 2 in your screenshot.

The hard-coded size of 16 is intentional because there are too many buttons. However, if 32px icons look too small on your screen (16px icons don't look small here), I could make the toolbar button size optional: 16 vs. "Follow the style".

**Comment by shlyakpavel** [comment]
> I could make the toolbar button size optional: 16 vs. "Follow the style".

 Sounds nice :)

**Comment by tsujan** [comment]
> I'm sorry for leaving so many issues :)

Don't be sorry! For me, this is a good opportunity to enhance FeatherNotes. I've received such series of good reports from a few users (about my own apps or LXQt's) and I really appreciate them.

**Comment by tsujan** [comment]
Done. Now, the default is that of the active style.

**Comment by shlyakpavel** [comment]
@tsujan it's now fine! Thanks!

**Comment by tsujan** [comment]
You're welcome!

I checked "Small toolbar icon" for myself.
