### ISSUE TITLE
Mac cmake support

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherNotes#76]
Would be great to port cmake changes from FeatherPad here :)

**Comment by tsujan** [comment]
I had a plan to do so because CMake provides a cleaner compilation and qmake has no bright future.

In the last 2 days I was busy with an "impossible" task but, at last, my stubbornness worked :D  I might polish my solution and do more tests tomorrow. After that, I'll start to add CMake support to FeatherNotes. So, it might take some time. Of course, I'll make mistakes in the APPLE and HAIKU parts and you'll correct them ;)

**Comment by shlyakpavel** [comment]
> Of course, I'll make mistakes in the APPLE and HAIKU parts and you'll correct them ;)

By the way, you can always run free VMware player just like I do. It's really handsome to test Haiku, Mac, ReactOS, *BSD or even Windows.

**Comment by tsujan** [comment]
I use VirtualBox. I experienced *BSD on it; it was Linux without Linux kernel. As for Windows, I was its user 14 years ago. Windows feels alien and uncomfortable when it comes to coding. I've never found a macOS ISO to install on VirtualBox. Haiku is a mystery to me: since its starting days, I had it on VirtualBox but I even don't know how to install a simple app on it, let alone Qt.

There are many things I need to learn about various OSs but most of my free time is taken by programming (my programs and LXQt). So, my focus is on Linux, the OS that I like and use.

**Comment by shlyakpavel** [comment]
> I use VirtualBox.

Is it okay for you in terms of performance? My low-power MacBook feels bad about it.

> As for Windows, I was its user 14 years ago. Windows feels alien and uncomfortable when it comes to coding.

And when it comes to any other kind of usage, too...

>I've never found a macOS ISO to install on VirtualBox.

[Here](https://applehint.com/t/download-all-macos-x-10-4-10-14-original/376), [here](https://archive.org/details/MacOSXHighSierra10.13) with a guide from [here](https://www.hackint0sh.org/how-to-install-macos-on-virtualbox/) or [here](https://www.intoguide.com/install-mac-os-x-yosemite-on-amd-processors-on-virtualbox/) (for AMD cpu)
> Haiku is a mystery to me: since its starting days, I had it on VirtualBox but I even don't know how to install a simple app on it, let alone Qt.

Why? It has a simple [package manager](https://en.wikipedia.org/wiki/Haiku_Depot) just like any linux distro. The terminal is powered with bash, so you really won't feel much difference.
> most of my free time is taken by programming (my programs and LXQt). 

That's really nice :)
P. S. If you once decide to Install Mac on VM you can always contact me via email. I'm experienced hackintosher so I'l probably be able to help you

**Comment by tsujan** [comment]
> Is it okay for you in terms of performance?

It has always worked fine here, whether before being bought by Oracle or after that.

Thanks a lot for the Mac links!

> Why? It has a simple package manager

Its directory hierarchy has been confusing to me -- as if there is none; those of *BSD and macOS are very familiar -- but I haven't dedicated enough time to it yet.

**Comment by data-man** [comment]
@tsujan 

Is that issue still appropriate?

**Comment by tsujan** [comment]
@data-man 
I'm not sure. I have and use only Linux and support UNIX too; the supports for other OS's are out of my control.

**Comment by tsujan** [comment]
On second thought, since the new cmake files are like those of FeatherPad, I think there's no reason to keep this open.

Closing...
